name: Deploy pre-built image to Docker
defaults:
  run:
    shell: bash -ieo pipefail {0}

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/${{ github.repository }}:latest

jobs:
  Build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v4

      - name: "Login to github docker registry"
        run: echo ${{ secrets.PATTOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: install ssh keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker-compose pull && docker-compose up -d && exit"
      - name: cleanup
        run: rm -rf ~/.ssh